import type { ProfessionalWork } from '@/lib/types'

export const professionalWork: ProfessionalWork[] = [
  {
    slug: 'snaplogic-automations-portal',
    title: 'SnapLogic Automations Portal',
    type: 'professional',
    role: 'Full-Stack Developer, Solution Architect',
    employer: 'Palo Alto Networks',
    timeline: 'Jul 2024 – Present',
    summary:
      'Designed, developed, and deployed a comprehensive internal developer portal serving 15+ team members with self-service SnapLogic pipeline operations.',
    context:
      'Internal teams needed self-service access to SnapLogic pipeline operations, reducing manual ticket creation and support burden.',
    challenge:
      'Building a full-stack platform integrating 7 external systems with AI-powered analysis, deployed across 5 Kubernetes environments.',
    architecture:
      'React 18 frontend with 48 shadcn/ui components communicating with an Express.js backend exposing 35+ REST API endpoints across 5 domains. Backend integrates 7 external services: JIRA (automated ticket creation), BigQuery (data persistence across 5 tables), Pub/Sub (async processing), Slack (real-time notifications), Vertex AI (LLM inference), SnapLogic Runtime API, and Datadog APM. Deployed to Google Kubernetes Engine with Helm charts, HPA auto-scaling (3–10 pods), Vault secret injection, and OTel observability.',
    implementation: [
      'Built responsive React 18 frontend with TypeScript, 48 shadcn/ui components, dynamic form system, and real-time status tracking',
      'Implemented Express.js backend with 35+ REST API endpoints organized across 5 domains: Form Submissions, Utilities, AI/ML, Analytics, and Administration',
      'Integrated Google Vertex AI (Gemini 2.5 Flash) for AI-powered story creation with 3x retry mechanism and exponential backoff',
      'Built 2 conversational AI agents powered by Gemini 2.5 Pro: Error Analysis Agent and Pipeline Performance Agent with multi-turn conversation support',
      'Designed Pipeline Performance Analysis engine with 2-step async workflow: pipeline export parsing followed by multi-dimensional metric computation',
      'Integrated 5 external services: JIRA, BigQuery, Pub/Sub, Slack, and Vertex AI',
      'Deployed to Kubernetes across 5 environments (dev/sit/qa/stg/prd) via Harness CI + Spinnaker CD, Kong ingress, Vault Agent sidecar, Datadog APM',
      'Implemented comprehensive CI/CD pipeline using Harness with Blackduck SCA, Checkmarx SAST scanning, Docker multi-stage builds',
      'Built self-service user registration system with OTP-based authentication, session management, and role-based access control',
    ],
    impact: [
      '15+ users actively using the platform',
      '35+ REST API endpoints across 5 domains',
      '99.95% uptime, exceeding 99.9% target',
      '<300ms API response times',
      '2 conversational AI agents powered by Gemini 2.5 Pro',
    ],
    technicalHighlights: [
      '48 shadcn/ui components with dynamic form system',
      'Express.js backend with 35+ REST API endpoints',
      'Vertex AI (Gemini 2.5 Flash + Pro) integration',
      'Kubernetes deployment with Helm, Vault, Datadog APM',
      'Harness CI/CD with Blackduck SCA, Checkmarx SAST',
    ],
    technologies: [
      'React 18',
      'TypeScript',
      'Vite',
      'Tailwind CSS',
      'shadcn/ui',
      'Express.js',
      'Node.js',
      'BigQuery',
      'Pub/Sub',
      'Vertex AI',
      'Kubernetes',
      'Helm',
      'Vault',
      'Datadog APM',
    ],
    metrics: [
      { label: 'Users', value: '15+' },
      { label: 'API Endpoints', value: '35+' },
      { label: 'Uptime', value: '99.95%' },
      { label: 'API Response', value: '<300ms' },
    ],
    featured: true,
    category: ['AI + Platform Engineering'],
    visualizationType: 'service-graph',
    order: 1,
  },
  {
    slug: 'attest-access-recertification',
    title: 'Project Attest — Access Recertification',
    type: 'professional',
    role: 'Full-Stack Developer, Solution Architect',
    employer: 'Palo Alto Networks',
    timeline: 'Jul 2024 – Present',
    summary:
      'Designed and built a full-stack access recertification platform that turns a quarterly privileged-access review of Workday security groups into a reproducible, audit-defensible evidence pack — 8 screens, 36 API endpoints, and 596 tests covering an append-only audit trail.',
    context:
      'Quarterly user access review (UAR) of privileged Workday security groups is an ITGC access control. An administrator imports the Workday extract, each security group is assigned a business owner, the owners certify every account as retain or revoke, and the system produces the CSV evidence that satisfies the control.',
    challenge:
      'The output is audit evidence, not a report. That turns two properties into hard requirements rather than nice-to-haves: the exports must regenerate byte-identically on demand, and the identity behind every decision must be impossible to forge or backdate. Both constraints reach back into parsing, storage ordering, and the request boundary.',
    architecture:
      'NestJS 11 on Node 22 backend with a React 19 + Vite 7 + Tailwind v4 client, compiled and served as static output by the API so one container image covers every environment.\n\nPersistence is Firestore with 12 entity schemas and 12 corresponding services, backed by 9 composite indexes. Cycles own their population as subcollections — security groups, lines, decisions, auto-dispositions, assignments, magic links, notifications, fulfilments — while persons and audit events live at the root and outlive any single cycle.\n\nTwo validation boundaries are duplicated deliberately: class-validator DTOs at the HTTP edge with whitelist and forbidNonWhitelisted rejecting unknown fields outright, and Zod at the Firestore edge validating on the way in and on the way out, so a document written by a script or an older build cannot poison a read.\n\nThe import is parse-then-commit. Preview parses and classifies entirely in memory and persists nothing, returning a preview id; commit writes the previewed population as the cycle baseline. Re-importing always creates a new cycle and never mutates an existing one.\n\nThe audit log is append-only by construction — the audit service exposes no update or delete method — and spans 19 distinct audited actions. The actor is always resolved from the SSO identity, never read from a request body.',
    implementation: [
      'Built the parsing core as pure, dependency-free functions that take an injected extract date rather than reading the clock — the property that makes exports reproducible and keeps sign-on thresholds from drifting day to day',
      'Matched spreadsheet headers by normalized name rather than position, so irregular and reordered columns in the source extract parse identically',
      'Encoded the extract\'s real conventions rather than the expected ones: booleans arrive as blank-or-Yes and never as No, so absent, empty, and No all resolve to false',
      'Resolved last sign-on per account rather than per row, so one person holding six groups carries one sign-on date across all six — non-null beats null, more recent wins',
      'Gated the leaver flag on having an email and not being external, which is what separates genuine leavers from system and partner accounts sharing the same blank status',
      'Wrote an explicit sort key onto every document, because Firestore guarantees no ordering across paginated queries and the evidence CSVs must regenerate byte-identically — ordering is an application-level property here, not a query-time one',
      'Built the CSV engine to a byte-level specification: UTF-8 with BOM, CRLF including the trailing row, every field always quoted, embedded quotes doubled, and no generation timestamp anywhere in the output',
      'Delivered 4 evidence exports — full population, decisions, revocations, and auto-closed accounts — plus an evidence pack bundling them with the original workbook in a store-only ZIP and a JSON manifest carrying per-file row counts and SHA-256 hashes',
      'Derived remediation actions at export time from the security group type through an explicit routing table, with a Manual — determine group type fallback rather than a silent guess when the type is absent',
      'Implemented reviewer magic links as 32 random bytes, SHA-256 hashed at rest, single-use, bound to a person and cycle, and expiring at the cycle due date',
      'Enforced 8 review rules server-side with dedicated test coverage: justification mandatory on revoke, no partial submission, no self-attestation, auto-closed lines accept no decision, closed cycles reject writes, audit entries carry the SSO-resolved identity, the secondary approver gains write access after the due date, and a job-based revoke routes to HR instead of a group edit',
      'Built a 5-step reminder cadence stored as an anchor plus a day offset rather than fixed dates, so extending a due date after launch still yields a defensible schedule; only the human-readable instruction and the on/off switch are accepted from storage, because the anchor, offset, kind, and audience are code',
      'Recorded failed notification deliveries rather than discarding them — an owner who never received the notice is a different control finding from one who ignored it',
      'Solved runtime configuration for a build-time-inlined client bundle by having the server inject a whitelisted environment block into the served HTML per request, with the client preferring it over build-time values, so a single image stays valid across environments',
      'Made the public environment surface an explicit whitelist rather than a filter of known secrets, with a test asserting no key matching SECRET, KEY, TOKEN, PASSWORD, CREDENTIAL, or PRIVATE can reach the browser, and escaped the injected payload so a value containing a closing script tag cannot break out of the element',
      'Shipped light and dark themes through a single data-theme attribute where the dark layer overrides design tokens only and restates no component rules, using role tokens instead of ramp steps, lifting the brand red in dark mode to clear WCAG AA, and applying the theme pre-paint to avoid a flash',
      'Diagnosed and fixed a boot-time configuration defect where the auth gate read its issuer at module scope before configuration was populated, leaving deployed endpoints unauthenticated while the logs reported a healthy start',
      'Replaced silent environment fallthrough with a boot-time failure on an unrecognized environment name, on the principle that failing to start beats starting unauthenticated',
      'Built a local OIDC provider for development — real discovery, authorization code with verified PKCE, token, userinfo, JWKS, and logout — excluded from the production build so reviewer and role flows could be exercised before identity-provider registration landed',
    ],
    impact: [
      'All 8 screens delivered end to end: import, owners, assign, campaign, email, reviewer, export, runbook',
      'Verified against the real pilot extract: 52 security groups, 1,105 access lines, 589 distinct people, 96 auto-closed, 1,009 to review',
      'Byte-identical evidence regeneration — no generation timestamp, application-level ordering, SHA-256 manifest per export',
      '596 test cases across server and client, including an acceptance suite pinned to the pilot extract date',
      'Caught and fixed a configuration defect that had left deployed endpoints serving unauthenticated',
      'Phases 1 through 4 implemented; phase 5 is UAT and defect fixing',
    ],
    technicalHighlights: [
      'Clock-free pure-function parsing core for reproducible output',
      'Byte-identical CSV engine with SHA-256 evidence manifest',
      'Append-only audit log across 19 actions with SSO-resolved actors',
      'Hashed, single-use, cycle-bound reviewer magic links',
      'Anchor-plus-offset reminder cadence over stored dates',
      'Whitelist-based runtime env injection into a build-time-inlined bundle',
      'Token-only dark mode with WCAG AA enforced by test',
    ],
    technologies: [
      'NestJS 11',
      'Node.js 22',
      'TypeScript',
      'React 19',
      'Vite 7',
      'Tailwind CSS v4',
      'React Query',
      'Firestore',
      'Zod',
      'Jest',
      'OIDC SSO',
      'Helm',
      'Kubernetes',
    ],
    metrics: [
      { label: 'Access Lines Certified', value: '1,105' },
      { label: 'API Endpoints', value: '36' },
      { label: 'Test Cases', value: '596' },
      { label: 'Enforcement Rules', value: '8' },
    ],
    roadmap: {
      summary:
        'Five-phase delivery — phases 1 through 4 implemented; phase 5 is UAT and defect fixing',
      phases: 5,
    },
    featured: true,
    category: ['Compliance Platform Engineering'],
    visualizationType: 'workflow',
    order: 2,
  },
  {
    slug: 'fw-flex-pipeline-redesign',
    title: 'FW_Flex Pipeline Redesign',
    type: 'professional',
    role: 'Lead Architect & Designer',
    employer: 'Palo Alto Networks',
    timeline: 'Jul 2024 – Present',
    summary:
      'Redesigned Firewall Flex integration architecture from 20 fragmented pipelines into a standardized, scalable architecture with reusable common pipelines.',
    context:
      '20 fragmented, independently maintained pipelines with duplicated logic, inconsistent error handling, and high maintenance burden.',
    challenge:
      'Consolidating disparate integration patterns into a unified, standardized architecture while maintaining pipeline availability during migration.',
    architecture:
      'Three-tier architecture: 3 reusable Common Pipelines (COM0001–COM0003) consolidating shared logic, 9 simplified Worker Pipelines with standardized interfaces, and a Centralized Logging Framework (COM0005) routed to Chronosphere. Multi-environment configuration strategy supporting Development, Staging, and Production with environment-specific endpoint management.',
    implementation: [
      'Designed Common Pipeline Framework (COM0001–COM0003) consolidating 5 duplicate TMS lookups, 3 duplicate CSP API calls, and 9 duplicate Hub API error handlers into shared, reusable components',
      'Established standardized naming convention (INTnnnn/COMnnnn) and unified 4 disparate logging patterns into 1 centralized logging framework (COM0005) routed to Chronosphere',
      'Created comprehensive technical specification document with snap-level implementation details, configuration matrices, and validation checklists',
      'Designed 3-tier acknowledgment error handling logic: Immediate Ack, Retry with Backoff, Dead-Letter Queue',
      'Implemented centralized error routing pattern ("Route to Error Pipeline") providing consistent observability and alerting',
      'Designed multi-environment configuration strategy supporting Development, Staging, and Production deployments',
      'Coordinated phased rollout strategy: common pipelines deployed first, followed by worker pipeline refactoring one pipeline at a time with validation at each stage',
    ],
    impact: [
      '66% snap reduction across all worker pipelines (278 to 94 snaps)',
      '164 redundant components eliminated',
      'Maintenance burden reduced by two-thirds',
      'Standardized naming convention (INTnnnn/COMnnnn)',
      'Unified 4 disparate logging patterns into 1 centralized framework',
    ],
    technicalHighlights: [
      '3 reusable Common Pipelines (COM0001–COM0003)',
      '9 simplified Worker Pipelines',
      'Centralized Logging Framework (COM0005)',
      '3-tier acknowledgment error handling',
      'Multi-environment configuration strategy',
    ],
    technologies: [
      'SnapLogic',
      'Pub/Sub',
      'Datadog',
      'Chronosphere',
    ],
    metrics: [
      { label: 'Snap Reduction', value: '66%' },
      { label: 'Before', value: '278 snaps' },
      { label: 'After', value: '94 snaps' },
      { label: 'Workers', value: '9 pipelines' },
    ],
    featured: true,
    category: ['Integration Architecture'],
    visualizationType: 'pipeline-architecture',
    order: 3,
  },
  {
    slug: 'pc-cc-bigquery-migration',
    title: 'PC → CC BigQuery Migration',
    type: 'professional',
    role: 'Solution Architect',
    employer: 'Palo Alto Networks',
    timeline: 'Jul 2024 – Present',
    summary:
      'Architected phased migration from Datadog state-store lookups to Google BigQuery for the Cortex-to-Cloud migration pipeline.',
    context:
      'Critical 15-day data retention risk with Datadog state-store lookups in the PC to CC migration pipeline.',
    challenge:
      'Designing a zero-data-loss migration with dual-write mechanism and phased rollout across 5 affected pipelines.',
    architecture:
      'Dual-write migration architecture: simultaneous writes to both Datadog and BigQuery with consistency validation before cutover. BigQuery schema designed with DATE partitioning and field clustering for optimized query performance. MERGE statements ensure idempotent operations, preventing duplicate records and enabling replay-safe processing.',
    implementation: [
      'Designed optimized BigQuery schema with DATE partitioning and field clustering for query performance',
      'Designed BigQuery MERGE statements ensuring idempotent operations, preventing duplicates, and enabling replay-safe processing',
      'Implemented zero-data-loss migration strategy using dual-write mechanism with consistency validation before cutover',
      'Specified changes across 5 affected pipelines: 7 snaps removed, 13 snaps added, 8 snaps modified, with detailed SQL queries and validation scripts',
      'Designed 4-phase rollout strategy: (1) Preparation and schema creation, (2) Dual-write with consistency monitoring, (3) Read migration with Datadog fallback, (4) Decommission legacy queries',
      'Identified and designed 13 additional improvements: 3 critical P0 (dead-letter table, event sourcing, automated reconciliation), plus P1–P3 enhancements',
      'Enabled BigQuery ML and Looker Studio dashboard capabilities for advanced analytics and executive reporting',
    ],
    impact: [
      '4-10x query latency improvement (2-5s to under 500ms)',
      '10-80x cost reduction per query',
      'Zero data loss during migration',
      'Eliminated 30-day data retention limit',
      '4-phase rollout strategy with Datadog fallback',
    ],
    technicalHighlights: [
      'BigQuery DATE partitioning and field clustering',
      'MERGE statements for idempotent operations',
      'Dual-write migration with consistency validation',
      '4-phase rollout strategy with fallback',
      '13 additional improvements identified (3 P0)',
    ],
    technologies: [
      'SnapLogic',
      'Google BigQuery',
      'Datadog',
      'Pub/Sub',
      'SQL',
    ],
    metrics: [
      { label: 'Latency Improvement', value: '4–10×' },
      { label: 'Cost Reduction', value: '10–80×' },
      { label: 'Data Loss', value: '0' },
      { label: 'Pipelines Affected', value: '5' },
    ],
    featured: true,
    category: ['Data Architecture'],
    visualizationType: 'migration-flow',
    order: 4,
  },
  {
    slug: 'rag-corpus-optimization',
    title: 'RAG Corpus Optimization',
    type: 'professional',
    role: 'GenAI Engineer',
    employer: 'Palo Alto Networks',
    timeline: 'Jul 2024 – Present',
    summary:
      'Engineered optimized RAG corpus reducing AI review inconsistency from ~40% to <5% through structured RAG design and deterministic system instructions.',
    context:
      'AI-powered pipeline reviews produced inconsistent results: missing rules, duplicates, and different output each run due to unstructured RAG corpus.',
    challenge:
      'Diagnosing root causes of inconsistency across the RAG architecture — PDF chunking, lack of output format, and missing deduplication instructions — and engineering a deterministic solution.',
    architecture:
      'Structured RAG corpus with atomic self-contained rule blocks, unique rule IDs, JSON path detection specifications, deduplication protocols, and deterministic output schema. 7-step optimization framework driving the corpus from v1.8 to v3.0.',
    implementation: [
      'Identified inconsistency root causes through systematic analysis: PDF chunking, no output format, no deduplication instructions',
      'Engineered optimized RAG corpus (v1.8 → v3.0) with atomic self-contained rule blocks, unique rule IDs, and JSON path detection specs',
      'Designed 7-step optimization framework: PDF→Markdown conversion, atomic rules, system behavior instructions, strict JSON output format, unique IDs, detection specs, master checklist',
      'Implemented 58→20 cluster deduplication for Error Report RAG, analyzing semantic similarity across cluster names and consolidating near-duplicates',
    ],
    impact: [
      'Reduced AI review inconsistency from ~40% to <5%',
      'Engineered corpus from v1.8 to v3.0',
      '58 → 20 cluster deduplication for Error Report RAG',
      '7-step optimization framework',
    ],
    technicalHighlights: [
      'Atomic self-contained rule blocks with unique IDs',
      'JSON path detection specifications',
      '7-step optimization framework',
      'Semantic similarity-based cluster deduplication',
    ],
    technologies: [
      'Vertex AI',
      'Gemini 2.5 Pro',
      'RAG',
      'Prompt Engineering',
      'SnapLogic',
    ],
    metrics: [
      { label: 'Inconsistency Before', value: '~40%' },
      { label: 'Inconsistency After', value: '<5%' },
      { label: 'Clusters Before', value: '58' },
      { label: 'Clusters After', value: '20' },
    ],
    featured: true,
    category: ['GenAI / RAG'],
    order: 5,
  },
  {
    slug: 'critical-incident-response',
    title: 'Critical Incident Response',
    type: 'professional',
    role: 'Incident Responder, Solution Architect',
    employer: 'Palo Alto Networks',
    summary:
      'Responded to P1 critical incident during quarter-end/year-end processing where all Licensing SnapLogic pipelines lost observability.',
    context:
      'During quarter-end/year-end critical processing period, all Licensing SnapLogic pipelines lost observability due to legacy Datadog API decommissioning.',
    challenge:
      'Restoring pipeline observability during a critical business period with zero tolerance for transaction monitoring gaps.',
    architecture:
      'Migrated logging from deprecated direct Datadog REST POST calls to enterprise Pub/Sub pattern with Chronosphere ingestion. Centralized observability restoration across all affected Licensing pipelines.',
    implementation: [
      'Identified root cause within 20 minutes: legacy custom logging implementation using direct REST POST calls to decommissioned Datadog API endpoint returning 404/401 errors',
      'Designed and implemented architectural fix within 30 minutes: migrated logging from deprecated direct API calls to enterprise Pub/Sub pattern with Chronosphere ingestion',
      'Restored full team observability within 60 minutes, achieving zero business impact during critical quarter-end period',
      'Documented executive-level Root Cause Analysis (RCA) covering timeline, root cause, contributing factors, resolution steps, corrective actions, and preventive recommendations',
      'Initiated audit of all other pipelines for similar legacy logging patterns, identifying and remediating additional instances proactively',
    ],
    impact: [
      'Root cause identified within 20 minutes',
      'Architectural fix designed and implemented within 30 minutes',
      'Full observability restored within 60 minutes',
      'Zero business impact during critical quarter-end period',
    ],
    technicalHighlights: [
      'Legacy Datadog API decommission diagnosis',
      'Pub/Sub + Chronosphere migration pattern',
      'Executive-level RCA documentation',
      'Proactive audit of related pipelines',
    ],
    technologies: [
      'SnapLogic',
      'Pub/Sub',
      'Chronosphere',
      'Datadog',
    ],
    metrics: [
      { label: 'Root Cause', value: '20 min' },
      { label: 'Fix Designed', value: '30 min' },
      { label: 'Restored', value: '60 min' },
      { label: 'Business Impact', value: '$0' },
    ],
    featured: true,
    category: ['Production Engineering'],
    order: 6,
  },
  {
    slug: 'quote-journey-tracker-agent',
    title: 'Quote Journey Tracker Agent',
    type: 'professional',
    role: 'AI Agent Architect & Developer',
    employer: 'Palo Alto Networks',
    summary:
      'Designed and deployed an AI-powered diagnostic agent on GCP Agent Studio that analyzes transactional logs from Chronosphere, matches against 23 documented quote debugging scenarios via RAG, and delivers structured root cause analysis via Slack DM — reducing investigation time from 3–4 minutes to 30–40 seconds.',
    context:
      'Quote processing investigations required manual log analysis across Chronosphere, taking 3–4 minutes per investigation with inconsistent diagnostic quality. Engineers had to manually cross-reference transactional logs against known issue patterns, producing variable-quality root cause assessments.',
    challenge:
      'Building an end-to-end AI diagnostic pipeline from portal trigger through log retrieval, RAG-based pattern matching against 23 documented scenarios, implementing anti-hallucination constraints for reliable diagnostics, and delivering structured results via Slack DM — with JIRA error-handling integration for failure cases.',
    architecture:
      'Integration pipeline: SnapLogic Automations Portal → GCP Pub/Sub filtered subscription → Chronosphere API log retrieval → GCP Agent Studio (Gemini 3.5 Flash foundation model + Vertex AI RAG Engine) → structured JSON → Slack DM delivery.\n\nRAG Engine configuration: Gemini 2.5 Flash for custom LLM parsing prompts, semantic chunking (size 500, overlap 100), built-in reranking with topK=20. Knowledge base contains 23 documented issue patterns as ground-truth diagnostic scenarios.\n\nSearch strategy: Narrow-then-wide fallback — primary Key_Tracking_ID query with full-text search fallback for unmatched cases.\n\nAuthentication: GCP Service Account with Agent Platform User role.\n\nError handling: Failures route to JIRA ticket updates with ai-audit-done / ai-audit-failed status transitions.',
    implementation: [
      'Designed and deployed AI diagnostic agent on GCP Agent Studio with Vertex AI RAG Engine and Gemini 3.5 Flash foundation model',
      'Built Vertex AI RAG Engine with custom LLM parsing prompts using Gemini 2.5 Flash reranker, semantic chunking (size 500, overlap 100), and topK=20 reranking',
      'Populated knowledge base with 23 documented quote debugging scenarios as ground-truth diagnostic patterns',
      'Implemented narrow-then-wide search fallback: primary Key_Tracking_ID query with full-text search fallback for unmatched cases',
      'Implemented 5 anti-hallucination constraints: (1) rule scoping — agent only applies rules from matched scenarios, (2) unknown sub-step handling — explicit "unknown" classification rather than inference, (3) error suffix classification — pattern-matched error categorization, (4) ground-truth error field validation — responses validated against documented error fields, (5) sub-step name isolation — prevents cross-contamination between diagnostic steps',
      'Designed structured JSON output schema: flow classification, processing summary, root cause analysis, Success / Failed / Inconclusive status determination, and prescriptive next steps',
      'Built end-to-end integration pipeline: SnapLogic Automations Portal trigger → GCP Pub/Sub filtered subscription → Chronosphere API log retrieval → Agent Studio diagnostic processing → structured JSON → Slack DM delivery',
      'Implemented error handling with JIRA ticket updates on failure, including ai-audit-done / ai-audit-failed status transitions via JIRA API',
      'Configured GCP Service Account authentication with Agent Platform User role for secure agent access',
      'Designed 5-phase evolution roadmap from reactive diagnostics to autonomous agent operations: 6 epics, 22+ user stories',
    ],
    impact: [
      'Investigation response time improved from 3–4 minutes to 30–40 seconds (85–90% reduction)',
      'Documented productivity impact: 540+ hours/year saved across the team',
      'Estimated ~$40,000+ annual productivity value',
      'Documented 2,000–3,000% ROI',
      '23 documented issue patterns in RAG knowledge base',
      '5 anti-hallucination constraints ensuring diagnostic reliability',
    ],
    technicalHighlights: [
      'GCP Agent Studio with Vertex AI RAG Engine',
      'Gemini 3.5 Flash foundation model + Gemini 2.5 Flash reranker',
      'Semantic chunking (size 500, overlap 100) with topK=20 reranking',
      '5 documented anti-hallucination constraints',
      'Narrow-then-wide search fallback strategy',
      'End-to-end integration: Portal → Pub/Sub → Chronosphere → Agent Studio → Slack',
    ],
    technologies: [
      'GCP Agent Studio',
      'Gemini 3.5 Flash',
      'Vertex AI RAG Engine',
      'Gemini 2.5 Flash',
      'SnapLogic',
      'GCP Pub/Sub',
      'Chronosphere',
      'Slack API',
      'JIRA API',
    ],
    metrics: [
      { label: 'Response Time Before', value: '3–4 min' },
      { label: 'Response Time After', value: '30–40 sec' },
      { label: 'Hours Saved/Year', value: '540+' },
      { label: 'Documented ROI', value: '2,000–3,000%' },
    ],
    evaluation: [
      { framework: 'RECIPE', score: '4.0 / 5' },
      { framework: 'CASE', score: '3.9 / 5' },
      { framework: 'COSTS', score: '4.5 / 5' },
      { framework: 'PATH', score: '3.9 / 5' },
      { framework: 'AI-First', score: '3.9 / 5' },
    ],
    roadmap: {
      summary: '5-phase evolution from reactive diagnostics to autonomous agent operations',
      phases: 5,
      epics: 6,
      stories: '22+',
    },
    featured: true,
    category: ['GenAI / AI Agents'],
    order: 7,
  },
  {
    slug: 'multi-agent-pipeline-review',
    title: 'Multi-Agent Pipeline Review System',
    type: 'professional',
    role: 'AI Agent Architect & Developer',
    employer: 'Palo Alto Networks',
    summary:
      'Designed, built, and deployed a production multi-agent system using Google ADK with ParallelAgent orchestrating 6 concurrent sub-agents for automated SnapLogic pipeline code review — achieving ~90% performance improvement over the sequential single-agent approach.',
    context:
      'SnapLogic pipeline code reviews required manual inspection against multiple rule categories covering naming conventions, best practices, error handling, performance, review conditions, and security. The initial sequential single-agent architecture processed all categories serially, creating a performance bottleneck that limited adoption.',
    challenge:
      'Converting the sequential single-agent review architecture into a parallel multi-agent system while maintaining structured output quality across 47+ rules, addressing regional model availability limitations for Gemini 3.5 Flash in us-west1, and iteratively refining agent instructions through production tuning cycles.',
    architecture:
      'Root LlmAgent → SequentialAgent → ParallelAgent (6 concurrent sub-agents) → Consolidator LlmAgent.\n\nSix specialized parallel sub-agents with documented rule counts: Naming (9 rules), Best Practices (6 rules), Error Handling (5 rules), Performance (8 rules), Review Conditions (8 critical + 18 warning), Security (1 rule).\n\nState management: output_key pattern for inter-agent communication — naming_result, best_practices_result, errorhandling_result, performance_result, review_result, security_result.\n\nModel routing: Custom GlobalGemini class extends ADK Gemini to route model calls to Google\'s global endpoint, addressing regional model availability limitation for Gemini 3.5 Flash in us-west1.\n\nConsolidation: Consolidator reads all six sub-agent results from session state and produces structured JSON: overall_status, critical_violations, warnings, category_breakdown, action_plan.\n\nDeployment: Google Cloud Agent Engine via adk deploy agent_engine, us-west1 region, with OpenTelemetry tracing via --otel_to_cloud for Cloud Trace.\n\nIntegration: SnapLogic streamQuery API with session-based architecture — create session → streamQuery with session_id → parse structured JSON response.',
    implementation: [
      'Designed ParallelAgent architecture orchestrating 6 concurrent specialized sub-agents, achieving ~90% performance improvement over sequential single-agent approach',
      'Built Naming sub-agent (9 rules) enforcing pipeline and snap naming conventions including INTnnnn/COMnnnn prefixes',
      'Built Best Practices sub-agent (6 rules) validating pipeline structure, documentation, and configuration patterns',
      'Built Error Handling sub-agent (5 rules) checking error routing, retry logic, and dead-letter patterns',
      'Built Performance sub-agent (8 rules) analyzing snap efficiency, connection patterns, and resource usage',
      'Built Review Conditions sub-agent covering 8 critical violations and 18 warning-level conditions',
      'Built Security sub-agent (1 rule) enforcing credential and secrets management patterns',
      'Implemented output_key state management pattern for inter-agent communication: naming_result, best_practices_result, errorhandling_result, performance_result, review_result, security_result',
      'Designed custom GlobalGemini class extending ADK Gemini to route model calls to Google\'s global endpoint, addressing regional Gemini 3.5 Flash availability limitation in us-west1',
      'Built Consolidator LlmAgent reading all six sub-agent results from session state, producing structured JSON: overall_status, critical_violations, warnings, category_breakdown, action_plan',
      'Deployed to Google Cloud Agent Engine using adk deploy agent_engine with OpenTelemetry tracing enabled via --otel_to_cloud for Cloud Trace',
      'Integrated with SnapLogic through streamQuery API with session-based architecture: create session → streamQuery with session_id → parse structured JSON response',
      'Iteratively refined agent instructions through 4 production tuning cycles based on real pipeline review feedback: connector-only retry rules, snap label reporting, error routing recognition, COEnnnn naming prefix acceptance',
    ],
    impact: [
      '~90% performance improvement from sequential to parallel agent architecture',
      '6 concurrent specialized review sub-agents',
      '47+ review rules across 6 categories',
      '4 production tuning cycles with iterative refinement',
      'Demonstrates AI-building-AI development approach using Cursor AI + Claude',
    ],
    technicalHighlights: [
      'Google ADK ParallelAgent → SequentialAgent → Consolidator architecture',
      'Custom GlobalGemini class for global endpoint routing',
      'output_key state management across 6 parallel agents',
      'Structured JSON consolidation from concurrent agent results',
      'Google Cloud Agent Engine deployment with OpenTelemetry / Cloud Trace',
      'AI-assisted development with Cursor AI + Claude',
    ],
    technologies: [
      'Google ADK',
      'Gemini 3.5 Flash',
      'Google Cloud Agent Engine',
      'Vertex AI Reasoning Engine',
      'SnapLogic',
      'Python',
      'OpenTelemetry',
      'Cloud Trace',
    ],
    metrics: [
      { label: 'Performance Improvement', value: '~90%' },
      { label: 'Parallel Sub-Agents', value: '6' },
      { label: 'Review Rules', value: '47+' },
      { label: 'Tuning Cycles', value: '4' },
    ],
    developmentApproach:
      'Built entirely using AI-assisted development with Cursor AI + Claude. AI assistance was used throughout architecture design, output_key pattern discovery, GlobalGemini implementation, deployment debugging, and iterative rule refinement across 4 production tuning cycles.',
    featured: true,
    category: ['GenAI / AI Agents'],
    order: 8,
  },
  {
    slug: 'snaplogic-naming-conventions-agent',
    title: 'SnapLogic Naming Conventions Agent',
    type: 'professional',
    role: 'AI Agent Developer',
    employer: 'Palo Alto Networks',
    summary:
      'Built a single-purpose LlmAgent using Google ADK that automatically renames SnapLogic pipeline snaps according to established CoE naming conventions — tracing execution order via link_map and generating sequentially numbered labels.',
    context:
      'After pipeline development in the Dev environment, snaps needed to be renamed to comply with established naming standards before promotion. This manual renaming process was repetitive, error-prone, and slowed down the development-to-promotion cycle.',
    challenge:
      'Parsing complete SnapLogic pipeline JSON, tracing execution order through link_map relationships (src_id → dst_id), and generating correctly sequenced snap labels while preserving the exact JSON structure with only 4 metadata fields modified.',
    architecture:
      'Single LlmAgent architecture using Google ADK with no sub-agents. Agent receives complete SnapLogic pipeline JSON, traces execution order via link_map (src_id → dst_id), and renames all enabled snaps using the naming standard: Number_ShapeType-Description.\n\nSequential numbering in multiples of 10 (10, 20, 30…) for execution snaps, multiples of 5 (15, 25…) for logging snaps. Only 4 metadata fields updated: pipeline purpose, pipeline notes, snap label, and snap notes. All other JSON structure preserved exactly.\n\nModel routing via custom GlobalGemini class routing to Google\'s global endpoint for Gemini 3.5 Flash. Output is minified JSON with link_map removed, ready for direct re-import into SnapLogic.',
    implementation: [
      'Built single-purpose LlmAgent using Google ADK that analyzes complete SnapLogic pipeline JSON and renames snaps to CoE naming standards',
      'Implemented execution order tracing via link_map (src_id → dst_id) to determine correct sequential numbering of snaps',
      'Enforced naming standard: Number_ShapeType-Description with sequential numbering in multiples of 10, logging snaps in multiples of 5',
      'Designed strict behavioral constraints: only enabled snaps processed, disabled snaps ignored, only 4 metadata fields updated',
      'Auto-generates pipeline purpose, pipeline notes, and per-snap notes describing each snap\'s function within the pipeline',
      'Implemented custom GlobalGemini class routing model calls to Google\'s global endpoint for Gemini 3.5 Flash availability',
      'Output is minified JSON maintaining exact input skeleton with link_map removed, ready for direct re-import',
    ],
    impact: [
      'Automated manual snap renaming process to CoE standards',
      'Eliminates human error in naming convention compliance',
      'Generates pipeline documentation (purpose, notes) automatically',
      'Reduces development-to-promotion cycle time',
      '~99.6% reduction in developer hours: 2–4 hours manual effort down to 30–60 seconds per pipeline',
    ],
    technicalHighlights: [
      'Google ADK LlmAgent with structured JSON input/output',
      'Pipeline execution order tracing via link_map graph',
      'Custom GlobalGemini class for global endpoint routing',
      'Strict 4-field-only update constraint preserving JSON fidelity',
    ],
    technologies: [
      'Google ADK',
      'Gemini 3.5 Flash',
      'Google Cloud Agent Engine',
      'Vertex AI Reasoning Engine',
      'SnapLogic',
      'Python',
    ],
    metrics: [
      { label: 'Time Before', value: '2–4 hrs' },
      { label: 'Time After', value: '30–60s' },
      { label: 'Developer Hours Saved', value: '~99.6%' },
    ],
    featured: false,
    category: ['GenAI / AI Agents'],
    order: 9,
  },
]
